// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_xDeLkTFer_kZ8UkMXKb28jzaY93zU0',
    appId: '1:81087630729:web:0a1bfaf6044183b4162558',
    messagingSenderId: '81087630729',
    projectId: 'chattingchatbot-53588',
    authDomain: 'chattingchatbot-53588.firebaseapp.com',
    storageBucket: 'chattingchatbot-53588.firebasestorage.app',
    measurementId: 'G-06TWGTRFF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqon-7skjN84JClSs5tXYaCXFSGysmdE',
    appId: '1:81087630729:android:30895d57946b60ea162558',
    messagingSenderId: '81087630729',
    projectId: 'chattingchatbot-53588',
    storageBucket: 'chattingchatbot-53588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP2CYiUzQ2qnzvoox1UWi82T0JmDZ_mxw',
    appId: '1:81087630729:ios:02be057a035b8a68162558',
    messagingSenderId: '81087630729',
    projectId: 'chattingchatbot-53588',
    storageBucket: 'chattingchatbot-53588.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP2CYiUzQ2qnzvoox1UWi82T0JmDZ_mxw',
    appId: '1:81087630729:ios:02be057a035b8a68162558',
    messagingSenderId: '81087630729',
    projectId: 'chattingchatbot-53588',
    storageBucket: 'chattingchatbot-53588.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_xDeLkTFer_kZ8UkMXKb28jzaY93zU0',
    appId: '1:81087630729:web:be349877bebeaafb162558',
    messagingSenderId: '81087630729',
    projectId: 'chattingchatbot-53588',
    authDomain: 'chattingchatbot-53588.firebaseapp.com',
    storageBucket: 'chattingchatbot-53588.firebasestorage.app',
    measurementId: 'G-SB8908P6Q1',
  );
}
